/**
 * Writes `src/data/saily-offered.generated.ts`: which of the plans in Saily's
 * partner API their own pages sell, and at what price.
 *
 *   npm run check:saily
 *
 * Why: on 9 October 2026, 150 of the API's 1,184 plans were not on the
 * saily.com page their link opens — Thailand unlimited for 7 days was
 * US$28.99 in the API, while the page sold a different plan at US$20.99. A
 * link to one opens on a plan the visitor did not choose, at a price we did
 * not show. So a Saily plan is listed only when its page sells it at the
 * API's price (`mapSailyPlan`). The owner allowed reading their pages for
 * this check, and only for it, on 9 October 2026.
 *
 * Why here and not on the live server: saily.com sits behind Cloudflare,
 * which answers some networks' requests with a challenge — this one's direct
 * address included — so the site itself could not count on reading the
 * pages. The live site reads only the API; this list says which of its plans
 * the pages sold when it was made. The nightly live check opens a sample of
 * the pages again and reports a listed plan they no longer sell; run this
 * script then, and release.
 *
 * What it reads: the API once, and of each page a plan could be listed on,
 * the first 96KB — the schema.org data ends within 41KB — four at a time.
 * Pages are fetched with curl, which goes through the environment's proxy.
 * Nothing is written when too few pages answered or too few plans matched:
 * the previous list stays.
 */
import { execFile } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { mapSailyPlan, sailyPlanPage } from '../src/lib/sources/saily/mapPlan';
import { sailyOffersInPage } from '../src/lib/sources/saily/offers';
import { SAILY_API } from '../src/lib/sources/saily/sailySource';
import type { SailyPlan } from '../src/lib/sources/saily/types';

const USER_AGENT = 'Mozilla/5.0 (compatible; yeshklita/1.0; +https://www.yeshklita.com)';
const READ_LIMIT_BYTES = 96 * 1024;
const CONCURRENCY = 4;
/** 1,184 plans and 1,020 sold as listed on 9 October 2026. */
const MIN_PLANS = 1000;
const MIN_OFFERED = 600;

function curl(url: string, limitBytes?: number): Promise<string> {
  const args = ['-sS', '-L', '-m', '60', '-A', USER_AGENT, '-w', '\n%{http_code}', url];
  if (limitBytes) args.unshift('-r', `0-${limitBytes - 1}`);
  return new Promise((done, fail) => {
    execFile('curl', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }, (_error, out) => {
      const cut = (out ?? '').lastIndexOf('\n');
      const status = (out ?? '').slice(cut + 1).trim();
      if (status !== '200' && status !== '206') fail(new Error(`HTTP ${status || 'no answer'} ← ${url}`));
      else done(out.slice(0, cut));
    });
  });
}

async function main() {
  const body = JSON.parse(await curl(SAILY_API)) as { items?: SailyPlan[] };
  const plans = body.items ?? [];
  if (plans.length < MIN_PLANS) throw new Error(`Saily API: only ${plans.length} plans`);

  // Only the pages of plans that could be listed at all.
  const candidates = plans.filter(
    (item) => 'plan' in mapSailyPlan(item, { affiliateId: '0', fetchedAt: '', offered: 'unchecked' }),
  );
  const pages = [...new Set(candidates.map(sailyPlanPage).filter((page): page is string => page !== null))];

  const sold = new Map<string, number>();
  const unread: string[] = [];
  let next = 0;
  const worker = async () => {
    while (next < pages.length) {
      const page = pages[next++];
      try {
        for (const [sku, cents] of sailyOffersInPage(await curl(page, READ_LIMIT_BYTES))) sold.set(sku, cents);
      } catch (error) {
        unread.push(String(error instanceof Error ? error.message : error));
      }
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  if (unread.length > pages.length * 0.05) {
    throw new Error(`${unread.length} of ${pages.length} pages did not answer:\n  ${unread.slice(0, 10).join('\n  ')}`);
  }

  // Kept: the plans whose page sells them at the API's price.
  const offered = candidates
    .filter((item) => sold.get(item.identifier) === item.price.amount_with_tax)
    .map((item) => [item.identifier, item.price.amount_with_tax] as const)
    .sort(([a], [b]) => a.localeCompare(b));
  if (offered.length < MIN_OFFERED) throw new Error(`only ${offered.length} of ${candidates.length} plans sold as listed`);

  const today = new Date().toISOString().slice(0, 10);
  const lines = [
    '// Generated by scripts/check-saily-pages.ts — do not edit by hand.',
    `// The plans in Saily's partner API that their own saily.com pages sold, at`,
    `// the API's price, on ${today}: ${offered.length} of ${candidates.length}. See the script for why.`,
    '',
    `export const sailyOfferedOn = '${today}';`,
    '',
    '/** Plan id → price in US cents, as both the API and the plan’s page stated it. */',
    'export const sailyOffered: Record<string, number> = {',
    ...offered.map(([id, cents]) => `  '${id}': ${cents},`),
    '};',
    '',
  ];
  writeFileSync(resolve(__dirname, '../src/data/saily-offered.generated.ts'), lines.join('\n'));

  const missing = candidates.length - offered.length;
  console.log(`Saily: ${plans.length} plans in the API, ${candidates.length} could be listed, ${pages.length} pages read`);
  console.log(`${offered.length} sold as listed; ${missing} not sold on their page at the API's price`);
  if (unread.length) console.log(`pages that did not answer (their plans are left out):\n  ${unread.join('\n  ')}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
