/**
 * Writes `src/data/alosim-pages.generated.ts`: where each aloSIM plan page
 * really lives now.
 *
 * Why: the Store API still hands out plan links in the old form,
 * alosim.com/he/united-states-esim?plan_id=…&affid=1810&oid=9. aloSIM moved
 * those pages under /destinations/, and their redirect from the old address
 * keeps the query in English but DROPS it in Hebrew — so a Hebrew visitor
 * landed on the country page with its default plan (5GB, 7 days for the US)
 * and without our affiliate id. Found 28 September 2026, from the owner's
 * report that the plan opened "with the right days but not the right data".
 *
 * The fix links both languages straight to the page's real address. This
 * script finds it the way a browser would: it asks for each English page with
 * no query and reads the `Location` header of the redirect. Nothing on the
 * page itself is read. One request at a time, each retried once.
 *
 *   NODE_USE_ENV_PROXY=1 npx tsx scripts/resolve-alosim-pages.ts [more-slugs.txt]
 *
 * Slugs come from the pages aloSIM registered for us, plus any in the
 * optional file (one per line) — e.g. every aloSIM page the live site links
 * to. Each ends up in one of three places:
 *
 *  - `alosimPagePaths`: the page moved, and is the same page — the last part
 *    of its new address is its old name (or a reviewed rename in SAME_PAGE).
 *  - `alosimDeadPages`: the page is gone (404), or now redirects to a
 *    different page (their "Eastern Europe" bundle goes to Europe), where the
 *    plan the visitor chose is not the one that opens. Those plans are not
 *    shown: every buy link must open the plan (the owner, 28 September 2026).
 *  - neither: no answer. Its plans keep aloSIM's own link, in English.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { alosimDestinations, alosimPageLinks } from '../src/data/alosim.generated';

const OUT = resolve(__dirname, '../src/data/alosim-pages.generated.ts');
const USER_AGENT = 'Mozilla/5.0 (compatible; yeshklita-link-check/1.0; +https://www.yeshklita.com)';
const TARGET = /^\/destinations\/(?:[a-z0-9-]+\/)*([a-z0-9-]+)\/$/u;

/**
 * Old name → new name, for pages aloSIM renamed but did not change. Each was
 * checked by hand; add one only after looking.
 */
const SAME_PAGE: Record<string, string> = {
  'the-united-republic-of-tanzania-esim': 'tanzania-esim',
};

async function locate(slug: string): Promise<{ status: number; location: string | null } | null> {
  for (let attempt = 0; attempt < 2; attempt += 1) {
    const response = await fetch(`https://alosim.com/${slug}`, {
      method: 'HEAD',
      redirect: 'manual',
      headers: { 'User-Agent': USER_AGENT },
      signal: AbortSignal.timeout(30_000),
    }).catch(() => null);
    if (response) return { status: response.status, location: response.headers.get('location') };
  }
  return null;
}

async function main() {
  const extra = process.argv[2]
    ? readFileSync(process.argv[2], 'utf8').split(/\s+/u).map((slug) => slug.trim()).filter(Boolean)
    : [];
  const slugs = [
    ...new Set([...alosimDestinations.map((destination) => destination.slug), ...Object.keys(alosimPageLinks), ...extra]),
  ]
    .filter((slug) => /^[a-z0-9-]+$/u.test(slug) && (slug.endsWith('-esim') || slug === 'central-america'))
    .sort();

  const pages: Record<string, string> = {};
  const dead: Record<string, string> = {};
  const unanswered: string[] = [];
  for (const slug of slugs) {
    const answer = await locate(slug);
    if (process.env.VERBOSE) console.error(slug, answer?.status ?? "no answer", answer?.location ?? "");
    if (!answer || answer.status >= 500) {
      unanswered.push(slug);
      continue;
    }
    if (answer.status === 404 || answer.status === 410) {
      dead[slug] = `HTTP ${answer.status}`;
      continue;
    }
    const path = answer.location ? new URL(answer.location, 'https://alosim.com').pathname : null;
    const name = path ? TARGET.exec(path)?.[1] : undefined;
    if (answer.status >= 300 && answer.status < 400 && path && name && (name === slug || SAME_PAGE[slug] === name)) {
      pages[slug] = path;
    } else if (answer.status >= 300 && answer.status < 400 && path) {
      dead[slug] = `redirects to ${path}`;
    } else {
      unanswered.push(`${slug} (HTTP ${answer.status})`);
    }
  }

  const quote = (text: string) => `'${text.replace(/'/g, "\\'")}'`;
  const pageLines = Object.entries(pages).map(([slug, path]) => `  ${quote(slug)}: ${quote(path)},`);
  const deadLines = Object.entries(dead).map(([slug, reason]) => `  ${quote(slug)}: ${quote(reason)},`);
  writeFileSync(
    OUT,
    `// Generated by scripts/resolve-alosim-pages.ts — do not edit by hand.
// Where each aloSIM page lives now, from aloSIM's own redirects, resolved
// ${new Date().toISOString().slice(0, 10)}. See the script for why.

/** Old address → the same page's current path (${pageLines.length} pages). */
export const alosimPagePaths: Record<string, string> = {
${pageLines.join('\n')}
};

/** Pages that are gone, or now lead to a different page (${deadLines.length}). Their plans are not shown. */
export const alosimDeadPages: Record<string, string> = {
${deadLines.join('\n')}
};
`,
  );
  console.log(`${pageLines.length} moved, ${deadLines.length} dead or elsewhere, ${unanswered.length} unanswered`);
  for (const [slug, reason] of Object.entries(dead)) console.log(`  dead: ${slug} — ${reason}`);
  for (const slug of unanswered) console.log(`  no answer: ${slug}`);
}

void main();
