// Generated by scripts/import-alosim-links.ts — do not edit by hand.
// Source: aloSIM's own Everflow export (Tracking & Asset Generator → Export List).
// Refresh by re-exporting and re-running the script; the diff is reviewable.

/** The two live aloSIM offers. Which one we actually use is set elsewhere. */
export const alosimOfferIds = [3, 9] as const;
export type AlosimOfferId = (typeof alosimOfferIds)[number];

export type AlosimDestination = {
  /** A single country, or one of their regional bundles. */
  kind: 'country' | 'region';
  /** aloSIM's own slug, as it appears in their store URL. */
  slug: string;
  /** aloSIM's own label for the page. */
  label: string;
  /** ISO 3166-1 alpha-2, or null for a regional bundle. */
  countryCode: string | null;
  /** The tracking link for each offer, exactly as aloSIM issued it. */
  links: Record<number, string>;
};

/** The affiliate id every link carries. Not a secret — it is in every link. */
export const alosimAffiliateId = '1810';

export const alosimDestinations: AlosimDestination[] = [
  {
    kind: 'country',
    slug: 'albania-esim',
    label: "Albania eSIM packages",
    countryCode: 'AL',
    links: {
      3: 'https://app.alosim.com/esim-store/country/albania-esim?uid=16&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/albania-esim?uid=428&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'anguilla-esim',
    label: "Anguilla eSIM packages",
    countryCode: 'AI',
    links: {
      3: 'https://app.alosim.com/esim-store/country/anguilla-esim?uid=17&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/anguilla-esim?uid=429&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'antigua-and-barbuda-esim',
    label: "Antigua and Barbuda eSIM packages",
    countryCode: 'AG',
    links: {
      3: 'https://app.alosim.com/esim-store/country/antigua-and-barbuda-esim?uid=18&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/antigua-and-barbuda-esim?uid=430&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'argentina-esim',
    label: "Argentina eSIM packages",
    countryCode: 'AR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/argentina-esim?uid=19&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/argentina-esim?uid=431&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'aruba-esim',
    label: "Aruba eSIM packages",
    countryCode: 'AW',
    links: {
      3: 'https://app.alosim.com/esim-store/country/aruba-esim?uid=20&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/aruba-esim?uid=432&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'australia-esim',
    label: "Australia eSIM packages",
    countryCode: 'AU',
    links: {
      3: 'https://app.alosim.com/esim-store/country/australia-esim?uid=21&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/australia-esim?uid=433&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'austria-esim',
    label: "Austria eSIM packages",
    countryCode: 'AT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/austria-esim?uid=22&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/austria-esim?uid=434&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bahamas-esim',
    label: "Bahamas eSIM packages",
    countryCode: 'BS',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bahamas-esim?uid=23&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bahamas-esim?uid=435&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bahrain-esim',
    label: "Bahrain eSIM packages",
    countryCode: 'BH',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bahrain-esim?uid=24&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bahrain-esim?uid=436&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bangladesh-esim',
    label: "Bangladesh eSIM packages",
    countryCode: 'BD',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bangladesh-esim?uid=25&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bangladesh-esim?uid=437&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'barbados-esim',
    label: "Barbados eSIM packages",
    countryCode: 'BB',
    links: {
      3: 'https://app.alosim.com/esim-store/country/barbados-esim?uid=26&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/barbados-esim?uid=438&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'belarus-esim',
    label: "Belarus eSIM packages",
    countryCode: 'BY',
    links: {
      3: 'https://app.alosim.com/esim-store/country/belarus-esim?uid=27&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/belarus-esim?uid=439&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'belgium-esim',
    label: "Belgium eSIM packages",
    countryCode: 'BE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/belgium-esim?uid=28&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/belgium-esim?uid=440&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bermuda-esim',
    label: "Bermuda eSIM packages",
    countryCode: 'BM',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bermuda-esim?uid=29&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bermuda-esim?uid=441&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bhutan-esim',
    label: "Bhutan eSIM packages",
    countryCode: 'BT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bhutan-esim?uid=30&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bhutan-esim?uid=442&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bolivia-esim',
    label: "Bolivia eSIM packages",
    countryCode: 'BO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bolivia-esim?uid=31&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bolivia-esim?uid=443&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'brazil-esim',
    label: "Brazil eSIM packages",
    countryCode: 'BR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/brazil-esim?uid=32&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/brazil-esim?uid=444&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'british-virgin-islands-esim',
    label: "British Virgin Islands eSIM packages",
    countryCode: 'VG',
    links: {
      3: 'https://app.alosim.com/esim-store/country/british-virgin-islands-esim?uid=33&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/british-virgin-islands-esim?uid=445&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'brunei-esim',
    label: "Brunei eSIM packages",
    countryCode: 'BN',
    links: {
      3: 'https://app.alosim.com/esim-store/country/brunei-esim?uid=34&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/brunei-esim?uid=446&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'bulgaria-esim',
    label: "Bulgaria eSIM packages",
    countryCode: 'BG',
    links: {
      3: 'https://app.alosim.com/esim-store/country/bulgaria-esim?uid=35&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/bulgaria-esim?uid=447&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'cambodia-esim',
    label: "Cambodia eSIM packages",
    countryCode: 'KH',
    links: {
      3: 'https://app.alosim.com/esim-store/country/cambodia-esim?uid=36&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/cambodia-esim?uid=448&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'canada-esim',
    label: "Canada eSIM packages",
    countryCode: 'CA',
    links: {
      3: 'https://app.alosim.com/esim-store/country/canada-esim?uid=37&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/canada-esim?uid=449&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'cayman-islands-esim',
    label: "Cayman Islands eSIM packages",
    countryCode: 'KY',
    links: {
      3: 'https://app.alosim.com/esim-store/country/cayman-islands-esim?uid=38&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/cayman-islands-esim?uid=450&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'chile-esim',
    label: "Chile eSIM packages",
    countryCode: 'CL',
    links: {
      3: 'https://app.alosim.com/esim-store/country/chile-esim?uid=39&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/chile-esim?uid=451&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'china-esim',
    label: "China eSIM packages",
    countryCode: 'CN',
    links: {
      3: 'https://app.alosim.com/esim-store/country/china-esim?uid=40&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/china-esim?uid=452&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'colombia-esim',
    label: "Colombia eSIM packages",
    countryCode: 'CO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/colombia-esim?uid=41&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/colombia-esim?uid=453&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'costa-rica-esim',
    label: "Costa Rica eSIM packages",
    countryCode: 'CR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/costa-rica-esim?uid=42&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/costa-rica-esim?uid=454&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'croatia-esim',
    label: "Croatia eSIM packages",
    countryCode: 'HR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/croatia-esim?uid=43&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/croatia-esim?uid=455&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'cyprus-esim',
    label: "Cyprus eSIM packages",
    countryCode: 'CY',
    links: {
      3: 'https://app.alosim.com/esim-store/country/cyprus-esim?uid=44&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/cyprus-esim?uid=456&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'czech-republic-esim',
    label: "Czech Republic eSIM packages",
    countryCode: 'CZ',
    links: {
      3: 'https://app.alosim.com/esim-store/country/czech-republic-esim?uid=45&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/czech-republic-esim?uid=457&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'denmark-esim',
    label: "Denmark eSIM packages",
    countryCode: 'DK',
    links: {
      3: 'https://app.alosim.com/esim-store/country/denmark-esim?uid=46&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/denmark-esim?uid=458&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'dominican-republic-esim',
    label: "Dominican Republic eSIM packages",
    countryCode: 'DO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/dominican-republic-esim?uid=47&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/dominican-republic-esim?uid=459&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'ecuador-esim',
    label: "Ecuador eSIM packages",
    countryCode: 'EC',
    links: {
      3: 'https://app.alosim.com/esim-store/country/ecuador-esim?uid=48&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/ecuador-esim?uid=460&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'egypt-esim',
    label: "Egypt eSIM packages",
    countryCode: 'EG',
    links: {
      3: 'https://app.alosim.com/esim-store/country/egypt-esim?uid=49&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/egypt-esim?uid=461&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'el-salvador-esim',
    label: "El Salvador eSIM packages",
    countryCode: 'SV',
    links: {
      3: 'https://app.alosim.com/esim-store/country/el-salvador-esim?uid=50&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/el-salvador-esim?uid=462&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'estonia-esim',
    label: "Estonia eSIM packages",
    countryCode: 'EE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/estonia-esim?uid=51&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/estonia-esim?uid=463&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'faroe-islands-esim',
    label: "Faroe Islands eSIM packages",
    countryCode: 'FO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/faroe-islands-esim?uid=52&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/faroe-islands-esim?uid=464&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'fiji-esim',
    label: "Fiji eSIM packages",
    countryCode: 'FJ',
    links: {
      3: 'https://app.alosim.com/esim-store/country/fiji-esim?uid=53&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/fiji-esim?uid=465&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'finland-esim',
    label: "Finland eSIM packages",
    countryCode: 'FI',
    links: {
      3: 'https://app.alosim.com/esim-store/country/finland-esim?uid=54&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/finland-esim?uid=466&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'france-esim',
    label: "France eSIM packages",
    countryCode: 'FR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/france-esim?uid=55&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/france-esim?uid=467&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'french-guiana-esim',
    label: "French Guiana eSIM packages",
    countryCode: 'GF',
    links: {
      3: 'https://app.alosim.com/esim-store/country/french-guiana-esim?uid=56&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/french-guiana-esim?uid=468&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'georgia-esim',
    label: "Georgia eSIM packages",
    countryCode: 'GE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/georgia-esim?uid=57&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/georgia-esim?uid=469&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'germany-esim',
    label: "Germany eSIM packages",
    countryCode: 'DE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/germany-esim?uid=58&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/germany-esim?uid=470&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'ghana-esim',
    label: "Ghana eSIM packages",
    countryCode: 'GH',
    links: {
      3: 'https://app.alosim.com/esim-store/country/ghana-esim?uid=59&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/ghana-esim?uid=471&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'gibraltar-esim',
    label: "Gibraltar eSIM packages",
    countryCode: 'GI',
    links: {
      3: 'https://app.alosim.com/esim-store/country/gibraltar-esim?uid=60&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/gibraltar-esim?uid=472&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'greece-esim',
    label: "Greece eSIM packages",
    countryCode: 'GR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/greece-esim?uid=61&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/greece-esim?uid=473&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'greenland-esim',
    label: "Greenland eSIM packages",
    countryCode: 'GL',
    links: {
      3: 'https://app.alosim.com/esim-store/country/greenland-esim?uid=62&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/greenland-esim?uid=474&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'guatemala-esim',
    label: "Guatemala eSIM packages",
    countryCode: 'GT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/guatemala-esim?uid=63&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/guatemala-esim?uid=475&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'hong-kong-esim',
    label: "Hong Kong eSIM packages",
    countryCode: 'HK',
    links: {
      3: 'https://app.alosim.com/esim-store/country/hong-kong-esim?uid=64&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/hong-kong-esim?uid=476&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'hungary-esim',
    label: "Hungary eSIM packages",
    countryCode: 'HU',
    links: {
      3: 'https://app.alosim.com/esim-store/country/hungary-esim?uid=65&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/hungary-esim?uid=477&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'iceland-esim',
    label: "Iceland eSIM packages",
    countryCode: 'IS',
    links: {
      3: 'https://app.alosim.com/esim-store/country/iceland-esim?uid=66&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/iceland-esim?uid=478&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'india-esim',
    label: "India eSIM packages",
    countryCode: 'IN',
    links: {
      3: 'https://app.alosim.com/esim-store/country/india-esim?uid=67&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/india-esim?uid=479&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'indonesia-esim',
    label: "Indonesia eSIM packages",
    countryCode: 'ID',
    links: {
      3: 'https://app.alosim.com/esim-store/country/indonesia-esim?uid=68&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/indonesia-esim?uid=480&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'ireland-esim',
    label: "Ireland eSIM packages",
    countryCode: 'IE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/ireland-esim?uid=69&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/ireland-esim?uid=481&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'isle-of-man-esim',
    label: "Isle of Man eSIM packages",
    countryCode: 'IM',
    links: {
      3: 'https://app.alosim.com/esim-store/country/isle-of-man-esim?uid=70&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/isle-of-man-esim?uid=482&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'israel-esim',
    label: "Israel eSIM packages",
    countryCode: 'IL',
    links: {
      3: 'https://app.alosim.com/esim-store/country/israel-esim?uid=71&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/israel-esim?uid=483&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'italy-esim',
    label: "Italy eSIM packages",
    countryCode: 'IT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/italy-esim?uid=72&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/italy-esim?uid=484&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'jamaica-esim',
    label: "Jamaica eSIM packages",
    countryCode: 'JM',
    links: {
      3: 'https://app.alosim.com/esim-store/country/jamaica-esim?uid=73&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/jamaica-esim?uid=485&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'japan-esim',
    label: "Japan eSIM packages",
    countryCode: 'JP',
    links: {
      3: 'https://app.alosim.com/esim-store/country/japan-esim?uid=74&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/japan-esim?uid=486&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'jersey-esim',
    label: "Jersey eSIM packages",
    countryCode: 'JE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/jersey-esim?uid=75&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/jersey-esim?uid=487&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'kazakhstan-esim',
    label: "Kazakhstan eSIM packages",
    countryCode: 'KZ',
    links: {
      3: 'https://app.alosim.com/esim-store/country/kazakhstan-esim?uid=76&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/kazakhstan-esim?uid=488&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'kuwait-esim',
    label: "Kuwait eSIM packages",
    countryCode: 'KW',
    links: {
      3: 'https://app.alosim.com/esim-store/country/kuwait-esim?uid=77&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/kuwait-esim?uid=489&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'latvia-esim',
    label: "Latvia eSIM packages",
    countryCode: 'LV',
    links: {
      3: 'https://app.alosim.com/esim-store/country/latvia-esim?uid=78&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/latvia-esim?uid=490&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'liechtenstein-esim',
    label: "Liechtenstein eSIM packages",
    countryCode: 'LI',
    links: {
      3: 'https://app.alosim.com/esim-store/country/liechtenstein-esim?uid=79&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/liechtenstein-esim?uid=491&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'lithuania-esim',
    label: "Lithuania eSIM packages",
    countryCode: 'LT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/lithuania-esim?uid=80&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/lithuania-esim?uid=492&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'luxembourg-esim',
    label: "Luxembourg eSIM packages",
    countryCode: 'LU',
    links: {
      3: 'https://app.alosim.com/esim-store/country/luxembourg-esim?uid=81&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/luxembourg-esim?uid=493&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'macau-esim',
    label: "Macau eSIM packages",
    countryCode: 'MO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/macau-esim?uid=82&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/macau-esim?uid=494&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'macedonia-esim',
    label: "Macedonia eSIM packages",
    countryCode: 'MK',
    links: {
      3: 'https://app.alosim.com/esim-store/country/macedonia-esim?uid=83&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/macedonia-esim?uid=495&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'malaysia-esim',
    label: "Malaysia eSIM packages",
    countryCode: 'MY',
    links: {
      3: 'https://app.alosim.com/esim-store/country/malaysia-esim?uid=84&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/malaysia-esim?uid=496&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'malta-esim',
    label: "Malta eSIM packages",
    countryCode: 'MT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/malta-esim?uid=85&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/malta-esim?uid=497&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'martinique-esim',
    label: "Martinique eSIM packages",
    countryCode: 'MQ',
    links: {
      3: 'https://app.alosim.com/esim-store/country/martinique-esim?uid=86&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/martinique-esim?uid=498&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'mayotte-esim',
    label: "Mayotte eSIM packages",
    countryCode: 'YT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/mayotte-esim?uid=87&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/mayotte-esim?uid=499&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'mexico-esim',
    label: "Mexico eSIM packages",
    countryCode: 'MX',
    links: {
      3: 'https://app.alosim.com/esim-store/country/mexico-esim?uid=88&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/mexico-esim?uid=500&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'moldova-esim',
    label: "Moldova eSIM packages",
    countryCode: 'MD',
    links: {
      3: 'https://app.alosim.com/esim-store/country/moldova-esim?uid=89&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/moldova-esim?uid=501&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'montenegro-esim',
    label: "Montenegro eSIM packages",
    countryCode: 'ME',
    links: {
      3: 'https://app.alosim.com/esim-store/country/montenegro-esim?uid=90&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/montenegro-esim?uid=502&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'myanmar-esim',
    label: "Myanmar eSIM packages",
    countryCode: 'MM',
    links: {
      3: 'https://app.alosim.com/esim-store/country/myanmar-esim?uid=91&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/myanmar-esim?uid=503&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'netherlands-esim',
    label: "Netherlands eSIM packages",
    countryCode: 'NL',
    links: {
      3: 'https://app.alosim.com/esim-store/country/netherlands-esim?uid=92&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/netherlands-esim?uid=504&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'new-zealand-esim',
    label: "New Zealand eSIM packages",
    countryCode: 'NZ',
    links: {
      3: 'https://app.alosim.com/esim-store/country/new-zealand-esim?uid=93&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/new-zealand-esim?uid=505&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'nicaragua-esim',
    label: "Nicaragua eSIM packages",
    countryCode: 'NI',
    links: {
      3: 'https://app.alosim.com/esim-store/country/nicaragua-esim?uid=94&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/nicaragua-esim?uid=506&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'nigeria-esim',
    label: "Nigeria eSIM packages",
    countryCode: 'NG',
    links: {
      3: 'https://app.alosim.com/esim-store/country/nigeria-esim?uid=95&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/nigeria-esim?uid=507&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'norway-esim',
    label: "Norway eSIM packages",
    countryCode: 'NO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/norway-esim?uid=96&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/norway-esim?uid=508&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'oman-esim',
    label: "Oman eSIM packages",
    countryCode: 'OM',
    links: {
      3: 'https://app.alosim.com/esim-store/country/oman-esim?uid=97&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/oman-esim?uid=509&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'pakistan-esim',
    label: "Pakistan eSIM packages",
    countryCode: 'PK',
    links: {
      3: 'https://app.alosim.com/esim-store/country/pakistan-esim?uid=98&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/pakistan-esim?uid=510&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'panama-esim',
    label: "Panama eSIM packages",
    countryCode: 'PA',
    links: {
      3: 'https://app.alosim.com/esim-store/country/panama-esim?uid=99&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/panama-esim?uid=511&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'paraguay-esim',
    label: "Paraguay eSIM packages",
    countryCode: 'PY',
    links: {
      3: 'https://app.alosim.com/esim-store/country/paraguay-esim?uid=100&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/paraguay-esim?uid=512&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'peru-esim',
    label: "Peru eSIM packages",
    countryCode: 'PE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/peru-esim?uid=101&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/peru-esim?uid=513&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'philippines-esim',
    label: "Philippines eSIM packages",
    countryCode: 'PH',
    links: {
      3: 'https://app.alosim.com/esim-store/country/philippines-esim?uid=102&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/philippines-esim?uid=514&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'poland-esim',
    label: "Poland eSIM packages",
    countryCode: 'PL',
    links: {
      3: 'https://app.alosim.com/esim-store/country/poland-esim?uid=103&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/poland-esim?uid=515&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'portugal-esim',
    label: "Portugal eSIM packages",
    countryCode: 'PT',
    links: {
      3: 'https://app.alosim.com/esim-store/country/portugal-esim?uid=104&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/portugal-esim?uid=516&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'qatar-esim',
    label: "Qatar eSIM packages",
    countryCode: 'QA',
    links: {
      3: 'https://app.alosim.com/esim-store/country/qatar-esim?uid=105&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/qatar-esim?uid=517&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'réunion-esim',
    label: "Réunion eSIM packages",
    countryCode: 'RE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/réunion-esim?uid=106&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/r%C3%A9union-esim?uid=518&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'romania-esim',
    label: "Romania eSIM packages",
    countryCode: 'RO',
    links: {
      3: 'https://app.alosim.com/esim-store/country/romania-esim?uid=107&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/romania-esim?uid=519&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'russia-esim',
    label: "Russia eSIM packages",
    countryCode: 'RU',
    links: {
      3: 'https://app.alosim.com/esim-store/country/russia-esim?uid=108&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/russia-esim?uid=520&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'saint-kitts-and-nevis-esim',
    label: "Saint Kitts and Nevis eSIM packages",
    countryCode: 'KN',
    links: {
      3: 'https://app.alosim.com/esim-store/country/saint-kitts-and-nevis-esim?uid=109&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/saint-kitts-and-nevis-esim?uid=521&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'saint-lucia-esim',
    label: "Saint Lucia eSIM packages",
    countryCode: 'LC',
    links: {
      3: 'https://app.alosim.com/esim-store/country/saint-lucia-esim?uid=110&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/saint-lucia-esim?uid=522&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'saint-vincent-esim',
    label: "Saint Vincent eSIM packages",
    countryCode: 'VC',
    links: {
      3: 'https://app.alosim.com/esim-store/country/saint-vincent-esim?uid=111&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/saint-vincent-esim?uid=523&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'san-marino-esim',
    label: "San Marino eSIM packages",
    countryCode: 'SM',
    links: {
      3: 'https://app.alosim.com/esim-store/country/san-marino-esim?uid=112&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/san-marino-esim?uid=524&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'saudi-arabia-esim',
    label: "Saudi Arabia eSIM packages",
    countryCode: 'SA',
    links: {
      3: 'https://app.alosim.com/esim-store/country/saudi-arabia-esim?uid=113&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/saudi-arabia-esim?uid=525&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'serbia-esim',
    label: "Serbia eSIM packages",
    countryCode: 'RS',
    links: {
      3: 'https://app.alosim.com/esim-store/country/serbia-esim?uid=114&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/serbia-esim?uid=526&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'singapore-esim',
    label: "Singapore eSIM packages",
    countryCode: 'SG',
    links: {
      3: 'https://app.alosim.com/esim-store/country/singapore-esim?uid=115&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/singapore-esim?uid=527&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'slovakia-esim',
    label: "Slovakia eSIM packages",
    countryCode: 'SK',
    links: {
      3: 'https://app.alosim.com/esim-store/country/slovakia-esim?uid=116&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/slovakia-esim?uid=528&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'slovenia-esim',
    label: "Slovenia eSIM packages",
    countryCode: 'SI',
    links: {
      3: 'https://app.alosim.com/esim-store/country/slovenia-esim?uid=117&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/slovenia-esim?uid=529&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'south-africa-esim',
    label: "South Africa eSIM packages",
    countryCode: 'ZA',
    links: {
      3: 'https://app.alosim.com/esim-store/country/south-africa-esim?uid=118&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/south-africa-esim?uid=530&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'south-korea-esim',
    label: "South Korea eSIM packages",
    countryCode: 'KR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/south-korea-esim?uid=119&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/south-korea-esim?uid=531&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'spain-esim',
    label: "Spain eSIM packages",
    countryCode: 'ES',
    links: {
      3: 'https://app.alosim.com/esim-store/country/spain-esim?uid=120&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/spain-esim?uid=532&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'sri-lanka-esim',
    label: "Sri Lanka eSIM packages",
    countryCode: 'LK',
    links: {
      3: 'https://app.alosim.com/esim-store/country/sri-lanka-esim?uid=121&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/sri-lanka-esim?uid=533&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'sweden-esim',
    label: "Sweden eSIM packages",
    countryCode: 'SE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/sweden-esim?uid=122&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/sweden-esim?uid=534&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'switzerland-esim',
    label: "Switzerland eSIM packages",
    countryCode: 'CH',
    links: {
      3: 'https://app.alosim.com/esim-store/country/switzerland-esim?uid=123&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/switzerland-esim?uid=535&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'taiwan-esim',
    label: "Taiwan eSIM packages",
    countryCode: 'TW',
    links: {
      3: 'https://app.alosim.com/esim-store/country/taiwan-esim?uid=124&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/taiwan-esim?uid=536&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'thailand-esim',
    label: "Thailand eSIM packages",
    countryCode: 'TH',
    links: {
      3: 'https://app.alosim.com/esim-store/country/thailand-esim?uid=125&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/thailand-esim?uid=537&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'tunisia-esim',
    label: "Tunisia eSIM packages",
    countryCode: 'TN',
    links: {
      3: 'https://app.alosim.com/esim-store/country/tunisia-esim?uid=126&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/tunisia-esim?uid=538&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'turkey-esim',
    label: "Turkey eSIM packages",
    countryCode: 'TR',
    links: {
      3: 'https://app.alosim.com/esim-store/country/turkey-esim?uid=127&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/turkey-esim?uid=539&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'turks-and-caicos-esim',
    label: "Turks and Caicos eSIM packages",
    countryCode: 'TC',
    links: {
      3: 'https://app.alosim.com/esim-store/country/turks-and-caicos-esim?uid=128&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/turks-and-caicos-esim?uid=540&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'ukraine-esim',
    label: "Ukraine eSIM packages",
    countryCode: 'UA',
    links: {
      3: 'https://app.alosim.com/esim-store/country/ukraine-esim?uid=129&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/ukraine-esim?uid=541&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'united-arab-emirates-(uae)-esim',
    label: "United Arab Emirates (UAE) eSIM packages",
    countryCode: 'AE',
    links: {
      3: 'https://app.alosim.com/esim-store/country/united-arab-emirates-(uae)-esim?uid=130&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/united-arab-emirates-(uae)-esim?uid=542&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'united-kingdom-(uk)-esim',
    label: "United Kingdom (UK) eSIM packages",
    countryCode: 'GB',
    links: {
      3: 'https://app.alosim.com/esim-store/country/united-kingdom-(uk)-esim?uid=131&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/united-kingdom-(uk)-esim?uid=543&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'united-states-(usa)-esim',
    label: "United States (USA) eSIM packages",
    countryCode: 'US',
    links: {
      3: 'https://app.alosim.com/esim-store/country/united-states-(usa)-esim?uid=132&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/united-states-(usa)-esim?uid=544&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'uruguay-esim',
    label: "Uruguay eSIM packages",
    countryCode: 'UY',
    links: {
      3: 'https://app.alosim.com/esim-store/country/uruguay-esim?uid=133&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/uruguay-esim?uid=545&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'uzbekistan-esim',
    label: "Uzbekistan eSIM packages",
    countryCode: 'UZ',
    links: {
      3: 'https://app.alosim.com/esim-store/country/uzbekistan-esim?uid=134&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/uzbekistan-esim?uid=546&oid=9&affid=1810',
    },
  },
  {
    kind: 'country',
    slug: 'vietnam-esim',
    label: "Vietnam eSIM packages",
    countryCode: 'VN',
    links: {
      3: 'https://app.alosim.com/esim-store/country/vietnam-esim?uid=135&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/country/vietnam-esim?uid=547&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'asia-all',
    label: "Asia packages (13 countries)",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/asia-all?uid=1334&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/asia-all?uid=1335&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'asia-five-pack-esim',
    label: "Asia packages (5 countries)",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/asia-five-pack-esim?uid=6&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/asia-five-pack-esim?uid=418&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'australia-and-nz-esim',
    label: "Australia and NZ eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/australia-and-nz-esim?uid=7&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/australia-and-nz-esim?uid=419&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'caribbean-esim',
    label: "Caribbean eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/caribbean-esim?uid=8&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/caribbean-esim?uid=420&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'eastern-europe-esim',
    label: "Eastern Europe eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/eastern-europe-esim?uid=9&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/eastern-europe-esim?uid=421&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'europe-esim',
    label: "Europe eSIM (32 countries)",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/europe-esim?uid=557&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/europe-esim?uid=560&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'mediterranean-esim',
    label: "Mediterranean eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/mediterranean-esim?uid=10&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/mediterranean-esim?uid=422&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'north-america-esim',
    label: "North America eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/north-america-esim?uid=11&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/north-america-esim?uid=423&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'scandinavia-esim',
    label: "Scandinavia eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/scandinavia-esim?uid=12&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/scandinavia-esim?uid=424&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'south-america-esim',
    label: "South America eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/south-america-esim?uid=13&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/south-america-esim?uid=425&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'uk-and-ireland-esim',
    label: "UK and Ireland eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/uk-and-ireland-esim?uid=14&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/uk-and-ireland-esim?uid=426&oid=9&affid=1810',
    },
  },
  {
    kind: 'region',
    slug: 'western-europe-esim',
    label: "Western Europe eSIM packages",
    countryCode: null,
    links: {
      3: 'https://app.alosim.com/esim-store/region/western-europe-esim?uid=15&oid=3&affid=1810',
      9: 'https://app.alosim.com/esim-store/region/western-europe-esim?uid=427&oid=9&affid=1810',
    },
  },
];
